### ISSUE TITLE
No longer compatible with version 2020.3

### ISSUE THREAD

**Issue by Tecktron** [matheusfm/json-utils-plugin#9]
IntelliJ auto-disabled this plugin stating it is no longer compatible. 
Are the plans to make this this compatible? Thanks.

**Comment by Amerousful** [comment]
I created pull request. Waiting for owner...)

**Comment by matheusfm** [comment]
Thanks for your PR! sorry for the late reply.

**Comment by matheusfm** [comment]
I have published the version 1.2: https://plugins.jetbrains.com/plugin/9775-json-utils

**Comment by Amerousful** [comment]
Thanks to you for such cool plugin :)
